config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '' => 'tracks#index'
  get 'tracks/:username' => 'tracks#show', as: :playlist
  get 'add-track' => 'tracks#add_track'
  post 'add-track' => 'tracks#create'
  get 'signup' => 'users#signup'
  post 'signup' => 'users#create'
  get 'login' => 'users#login'
  post 'login' => 'users#authenticate'
  delete 'logout' => 'users#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tracks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user 

  def current_user 
    @current_user ||= User.find_by_username(session[:username]) if session[:username] 
  end

  def login_required 
    redirect_to '/login' unless current_user 
  end

end

app/controllers/old_tracks_controller.rb
class TracksController < ApplicationController
  before_action :login_required, only: [:add_track, :create]

  def index
  end
  def playlist
    @tracks = Track.all
  end
  def add_track
    puts('user')
    puts(current_user.username)
    #@track = Track.new
    @track = current_user.tracks.new
  end
  def create
    #@track = Track.new(message_params)
    @track = current_user.tracks.new(message_params)
    puts(@current_user)
    #@track.user = @current_user
    if @track.save
      redirect_to '/tracks'
    else
      render 'add_track'
    end
  end
  private 
    def message_params 
      params.require(:track).permit(:name, :artist, :link)#.merge(user: current_user)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :login_required, only: [:add_track, :create]

  def index
    @title = 'Top Playlists'
    session['error'] = nil
    @top_playlists = User.joins(:tracks).group('users.id')
  end

  def playlist
    session['error'] = nil
    @tracks = Track.all
  end

  def add_track
    @title = 'Add New Track'
    session['error'] = nil
    @track = current_user.tracks.new
  end

  def show
    @title = params[:username] + "'s " + 'Playlist'
    session['error'] = nil
    @user = User.find_by_username(params[:username])
    if @user
      @tracks = @user.tracks
    else
      @tracks = []
      session['error'] = 'User does not exist!'
    end
  end

  def create
    session['error'] = nil
    @track = current_user.tracks.new(message_params)
    if @track.save
      redirect_url = '/tracks/' + current_user.username
      redirect_to redirect_url
    else
      render 'add_track'
    end
  end

  private 
    def message_params 
      params.require(:track).permit(:name, :artist, :link)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
    if current_user
      return redirect_to '/'
    end
    @title = 'Signup'
    session['error'] = nil 
    @user = User.new
  end

  def create
    session['error'] = nil
    if User.find_by_username(user_params[:username])
        session['error'] = 'Username already exists!'
        @user = User.new
        render 'signup'
    else
      @user = User.new(user_params)
      if @user.save
        session[:username] = @user.username
        redirect_url = '/tracks/' + @user.username
        redirect_to redirect_url
      else
        session['error'] = 'Sorry, you were not able to create an account'
        render 'signup' 
      end
    end
  end

  def login
    if current_user
      return redirect_to '/'
    end
    @title = 'Login'
    session['error'] = nil
  end
  
  def authenticate
    session['error'] = nil
    @user = User.find_by_username(params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:username] = @user.username
      redirect_url = '/tracks/' + @user.username
      redirect_to redirect_url
    else
      session['error'] = 'Incorrect username or password'
      render 'login'
    end
  end

  def logout
    session['error'] = nil
    session[:username] = nil
    redirect_to '/'
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Playlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Playlists</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "My Playlist", playlist_path(current_user, :username => current_user.username), class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', '/login', class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Signup', '/signup', class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

        <% if current_user %>
          <ul class="navbar-nav">
            <%= link_to "Logout", logout_path, method: "delete", class: 'nav-link' %>
          </ul>
        <% end %>
      </div>
    </nav>

    <div class="container-fluid" style="position: relative; top:75px;">
      <div class="row">
        <div class="col-sm-10 offset-sm-1">
          <h1 align="center"><%= @title %> </h1>
          <% if session['error'] %>
            <div class="alert alert-warning" role="alert">
              <%= session['error'] %>
            </div>
          <% end %>
          <%= yield %>
        </div> 
      </div>
    </div>
  </body>
</html>

app/views/tracks/add_track.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <%= form_for(@track, url: { action: 'create' }) do |f| %>
      <div class="form-group">
        <%= f.text_field :name, :placeholder => 'Track Name', class: 'form-control', :required => true %>
      </div>
      <div class="form-group">
        <%= f.text_field :artist, :placeholder => 'Artist Name', class: 'form-control', :required => true %>
      </div>  
      <div class="form-group">    
        <%= f.text_field :link, :placeholder => 'Link', class: 'form-control', :required => true %>
      </div>
      <%= f.submit "Add Track", class: 'btn btn-outline-primary' %> 
    <% end %>
  </div>
</div>

app/views/tracks/index.html.erb
<div class="row">
  <% if @top_playlists.length == 0 %>
    No playlists have been added yet
  <% end %>
  <% @top_playlists.each do |playlist| %>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header">
          @<%= playlist.username %>'s Playlist <span class="badge badge-primary badge-pill"><%= playlist.tracks.length %> track<% if playlist.tracks.length > 1 %>s<% end %></span>
        </div>
        <div class="card-body">
          <h5 class="card-title"></h5>
          <p class="card-text">
            <% playlist.tracks.first(3).each_with_index do |track, index| %>
              <div class="row">
                <div class="col-sm-10">
                  <%= index+1 %>.
                  <strong><%= track.name %></strong> by
                  <%= track.artist %>
                </div>
                <div class="col-sm-2">
                  <% if track.link.start_with?('https://www.youtube.com/watch?v=') %>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#playModal" data-url="<%= track.link %>" data-youtube="<%= track.link.split('&').first.sub("watch?v=", "embed/") %>" data-track="<%= track.name %>" data-artist="<%= track.artist %>">
  &#9654;
                    </button>
                  <% else %>
                    <%= link_to raw('&#9654;'), track.link, target: '_blank', class: 'btn btn-primary btn-sm' %>
                  <% end %>
                </div>
              </div>
              <hr>
            <% end %>
          </p>
          <div align="center">
            <%= link_to "View Playlist", playlist_path(playlist, :username => playlist.username), class: "btn btn-outline-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="playModal" tabindex="-1" role="dialog" aria-labelledby="playModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="playModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe id="ytplayer" type="text/html" width="640" height="360"
  src=""
  frameborder="0"></iframe>
        <br>
        Track not playing? Click <a href="" id="modal-url" target="_blank">here </a>to view it in a new tab

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  var player = document.getElementById('ytplayer');
  var direct_youtube_link = document.getElementById('modal-url')
  $('#playModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var embed_url = button.data('youtube') // Extract info from data-* attributes
    player.src = embed_url;
    var url = button.data('url')
    direct_youtube_link.href = url;
    var track = button.data('track')
    var artist = button.data('artist')
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text(track + ' by ' + artist)
  })

  $('#playModal').on('hide.bs.modal', function (event) {
    player.src = ""
  })
</script>

app/views/tracks/show.html.erb
<div class="row">
  <div class="col-sm-8">
    <% if current_user && current_user.username == params[:username] %>
      <%= link_to 'Add Track', '/add-track', class: 'btn btn-outline-success' %><br><br>
    <% end %>
    <% if @tracks.length > 0 %>
      <ul class="list-group">
      <li class="list-group-item list-group-item-light">
        @<%= @user.username %>'s Playlist <span class="badge badge-primary badge-pill"><%= @tracks.length %> track<% if @tracks.length > 1 %>s<% end %></span>
      </li>
      <% @tracks.each_with_index do |track, index| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-10">
              <%= index+1 %>.
              <strong><%= track.name %></strong> by
              <%= track.artist %>
            </div>
            <div class="col-sm-2">
              <% if track.link.start_with?('https://www.youtube.com/watch?v=') %>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#playModal" data-url="<%= track.link %>" data-youtube="<%= track.link.split('&').first.sub("watch?v=", "embed/") %>" data-track="<%= track.name %>" data-artist="<%= track.artist %>">&#9654;
                  </button>
                <% else %>
                  <%= link_to raw('&#9654;'), track.link, target: '_blank', class: 'btn btn-primary btn-sm' %>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      There are no tracks in this playlist
    <% end %>
    <br><br>
  </div>
</div>

<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="playModal" tabindex="-1" role="dialog" aria-labelledby="playModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="playModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">         
        <iframe id="ytplayer" type="text/html" width="640" height="360"
  src=""
  frameborder="0"></iframe>
        <br>
        Track not playing? Click <a href="" id="modal-url" target="_blank">here </a>to view it in a new tab 

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  var player = document.getElementById('ytplayer');
  var direct_youtube_link = document.getElementById('modal-url')

  $('#playModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var embed_url = button.data('youtube') // Extract info from data-* attributes
    player.src = embed_url;
    var url = button.data('url')
    direct_youtube_link.href = url;
    var track = button.data('track')
    var artist = button.data('artist')
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.  
    var modal = $(this)
    modal.find('.modal-title').text(track + ' by ' + artist)
  })

  $('#playModal').on('hide.bs.modal', function (event) {
    player.src = ""
  })
</script>

app/views/users/login.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_for(:user, url: { action: 'authenticate' }) do |f| %> 
      <div class="form-group">
        <%= f.text_field :username, :placeholder => 'Username', class: 'form-control', :required => true %>
      </div>
      <div class="form-group">  
        <%= f.password_field :password, :placeholder => 'Password', class: 'form-control', :required => true %>
      </div>  
      <%= f.submit "Login", class: 'btn btn-outline-primary' %> 
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_for(@user, url: { action: 'create' }) do |f| %>
      <div class="form-group">
        <%= f.text_field :username, :placeholder => 'Username', class: 'form-control', :required => true %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, :placeholder => 'Password', class: 'form-control', :required => true %>
      </div>
      <%= f.submit "Signup", class: 'btn btn-outline-primary' %>
    <% end %>
  </div>
</div>
~          